Add makefiles for building Utilities with GCC
calc84maniac/tiboyce pull request #213
Opened 2024-06-07 00:41 UTC by Redcarred2

Title is self explanatory, build works on my system

2024-06-08 15:30 UTC, calc84maniac requested changes

2024-06-08 15:30 UTC, calc84maniac commented on tiboyce-convertsav/Makefile
> +TARGET = convertsav
I'd prefer the target name be prefixed with `tiboyce-` to match with the Windows build and make the executable clearly identifiable

2024-06-08 15:30 UTC, calc84maniac commented on tiboyce-convertsav/Makefile
> +	rm -f $(TARGET)
You probably want to remove the OBJS files here, too (if they're being built at all? if they're not, then either add a rule for them or remove the OBJS definition)

2024-06-09 00:07 UTC, Redcarred2 commented
I have implemented the requested changes.

2024-06-09 01:24 UTC, merged